### ISSUE TITLE
Discrepancy with SPGL1.m

### ISSUE THREAD

**Issue by una-dinosauria** [slimgroup/GenSPGL.jl#1]
I recently tried to use this package as a replacement for the matlab version, only to find that I get very different results from the original implementation. I've been able to pin it down (I think) to the way the relative gap is computed. In SPGL1, the gap [is computed as follows](https://github.com/mpf/spgl1/blob/master/spgl1.m#L354-L355):

```maltab
 gap     = r'*(r-b) + tau*gNorm;
 rGap    = abs(gap) / max(1,f);
```

while in this package it is computed using [this formula](https://github.com/slimgroup/GenSPGL.jl/blob/master/src/spglcore.jl#L65-L66):

```julia
  Err = norm(init.x - tmp_proj)
  rErr = Err/max(1,init.f)
```

I assume that the goal of this package is to reproduce the matlab results, but this different seems to be intentional. What is the rational behind it?

If I've simply found a bug, I'm happy to debug further and submit a PR that fixes my use case.

**Comment by henryk-modzelewski** [comment]
Sorry for the confusion. GenSPGL is not the same solver as SPGL1. It was adopted from SPGL1, but extended and generalized. We will update README shortly to express it more clearly and highlight the differences.

We intend to work in the future on porting exact SPGL1 to Julia, but it is not at the moment at the top of our priorities.

Thanks for your comment. And we will definitely double-check your concerns.

**Comment by una-dinosauria** [comment]
Oh thanks! No worries, it makes sense now.
