### ISSUE TITLE
LoadError: syntax: incomplete: "function" at TraceNorm_project.jl:6 requires end

### ISSUE THREAD

**Issue by mikeando** [slimgroup/GenSPGL.jl#2]
I get the 

`LoadError: syntax: incomplete: "function" at TraceNorm_project.jl:6 requires end`

error when `using GenSPGL` on julia 0.6.2

The offending piece in `TraceNorm_project.jl` seems to be this:

~~~
if isapprox(norm(x), 0.0) && warn("norm(x) cannot be 0 in TraceNorm_project")
~~~

and commenting it out seems to make it all work.

**Comment by klensink** [comment]
Thanks for reporting this, it looks like it was meant to be a short circuit so the `if` statement isn't necessary.

If you submit a PR with the `if` removed I'll accept it.

**Comment by mikeando** [comment]
Pull request in PR #3

**Comment by klensink** [comment]
@mikeando Thanks!

@henryk-modzelewski  Just so you see this.
